ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - "@ast-grep/lang-angular"
  - "@ast-grep/lang-bash"
  - "@ast-grep/lang-c"
  - "@ast-grep/lang-cpp"
  - "@ast-grep/lang-csharp"
  - "@ast-grep/lang-css"
  - "@ast-grep/lang-dart"
  - "@ast-grep/lang-elixir"
  - "@ast-grep/lang-go"
  - "@ast-grep/lang-haskell"
  - "@ast-grep/lang-html"
  - "@ast-grep/lang-java"
  - "@ast-grep/lang-javascript"
  - "@ast-grep/lang-json"
  - "@ast-grep/lang-kotlin"
  - "@ast-grep/lang-lua"
  - "@ast-grep/lang-php"
  - "@ast-grep/lang-python"
  - "@ast-grep/lang-ruby"
  - "@ast-grep/lang-rust"
  - "@ast-grep/lang-scala"
  - "@ast-grep/lang-sql"
  - "@ast-grep/lang-swift"
  - "@ast-grep/lang-toml"
  - "@ast-grep/lang-tsx"
  - "@ast-grep/lang-typescript"
  - "@ast-grep/lang-yaml"
